server:
  port: ${PORT_AUTH:8081}

grpc:
  server:
    port: ${GRPC_PORT_AUTH:9081}
  client:
    user-service:
      address: ${USER_SERVICE_GRPC_URL}
      negotiation-type: plaintext

jwt:
  access:
    secret: ${JWT_ACCESS}
    ttl-minutes: ${JWT_ACC_TTL_MINS}
  refresh:
    secret: ${JWT_REFRESH}
    ttl-days: ${JWT_REF_TTL_DAYS}

spring:
  datasource:
    url: ${DB_URL_AUTH}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service
