server:
  port: ${PORT_AUTH:8441}
  ssl:
    enabled: false

grpc:
  server:
    port: ${GRPC_PORT_AUTH:9081}
  client:
    user-service:
      address: ${USER_SERVICE_GRPC_URL}
      negotiation-type: plaintext

jwt:
  issuer: ${JWT_ISSUER}
  public-key: ${JWT_PUBLIC_KEY}
  private-key: ${JWT_PRIVATE_KEY}
  access:
    ttl-minutes: ${JWT_ACC_TTL_MINS}
  refresh:
    ttl-days: ${JWT_REF_TTL_DAYS}

spring:
  datasource:
    url: ${DB_URL_AUTH}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service
