server:
  port: ${PORT_CATALOG:8083}

grpc:
  server:
    port: ${GRPC_PORT_CATALOG:9083}
  client:
    user-service:
      address: ${USER_SERVICE_GRPC_URL}
      negotiation-type: plaintext

spring:
  datasource:
    url: ${DB_URL_CATALOG}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: catalog-service
