server:
  port: 8083

grpc:
  client:
    user-service:
      address: static://catalog-service:9082
      negotiation-type: plaintext
  server:
    port: 9083

spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/catalog-db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: catalog-service