server:
  port: ${PORT_GATEWAY:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:${PORT_AUTH}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: http://user-service:${PORT_USER}
              predicates:
                - Path=/api/v1/user/**
            - id: catalog-service
              uri: http://catalog-service:${PORT_CATALOG}
              predicates:
                - Path=/api/v1/catalog/**
            - id: ai-service
              uri: http://ai-service:${PORT_AI}
              predicates:
                - Path=/api/v1/ai/**

jwt:
  secret: ${JWT_PUBLIC_KEY}