server:
  port: ${PORT_AI:8084}

spring:
  application:
    name: ai-service

openai:
  proxy: ${OPENAI_PROXY}
  key: ${OPENAI_KEY}
  model: ${OPENAI_MODEL}

grpc:
  client:
    user-service:
      address: ${USER_SERVICE_GRPC_URL}
      negotiation-type: plaintext
