server:
  port: ${PORT_USER:8082}

grpc:
  server:
    port: ${GRPC_PORT_USER:9082}
  client:
    catalog-service:
      address: ${CATALOG_SERVICE_GRPC_URL}
      negotiation-type: plaintext
    auth-service:
      address: ${AUTH_SERVICE_GRPC_URL}
      negotiation-type: plaintext

spring:
  datasource:
    url: ${DB_URL_USER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service
