server:
  port: 8082

grpc:
  client:
    catalog-service:
      address: static://catalog-service:9083
      negotiation-type: plaintext
    auth-service:
      address: static://auth-service:9081
      negotiation-type: plaintext
  server:
    port: 9082

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user-db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service